# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('rate', models.FloatField(default=1)),
                ('duration', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
