# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_calls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calls',
            new_name='Call',
        ),
    ]
