# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_call_target_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='timeofcall',
            field=models.TimeField(default=datetime.datetime(2017, 2, 26, 23, 7, 0, 171976, tzinfo=utc)),
        ),
    ]
