# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0006_call_timeofcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='timeofcall',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 23, 7, 41, 677516, tzinfo=utc)),
        ),
    ]
